language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: trusty

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: linux
      python: 3.6
      env:
        - PYTHON_VER=3.6
        - DOCS=1

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
    # Create test environment for package
  - conda env create -f kgp_env.yml
  - conda activate kgp
  - if [[ $DOCS ]]; then conda install sphinx; fi
  - pip install -e .

script:
  - kugupu -h
  #- pytest -v --cov=kugupu kugupu/tests/

after_success:
  - if [[ $DOCS ]]; then python setup.py build_sphinx; fi

notifications:
    email: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
  local_dir: build/sphinx/html
  project_name: kugupu
