name: Python Package using Micromamba

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v2.0.4
      with:
        environment-file: environment.yml
        cache-environment: true
        create-args: >-
          python=${{ matrix.python-version }}
          pip
          pytest
          pytest-cov
        init-shell: bash
    - name: build
      shell: bash -el {0}
      run: |
        python -m pip install . -e --no-deps --force-reinstall
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        python -m pytest
    - name: Codecov
      uses: codecov/codecov-action@v5.4.0
